version: 1.0.{build}

clone_folder: c:\dev2\node-mapnik

environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: s1us6xb8U2EqlaVYtoVMtulfgMdX4VVEKgTF+Eft104gWja1GG0Blf6cMJtG7Yu3
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10

platform:
#  - x64
  - x86

# branches to build
branches:
  # whitelist
  only:
    - master

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  # to run script as a PowerShell command prepend it with ps:
  # batch commands start from cmd:
  - echo WindowsSDKDir
  - echo %WindowsSDKDir%
  #- echo %PATH%
  #- SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  #- echo %PATH%
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  #- npm install -g node-gyp
  #- node-gyp --version
  #- where node
  #- cd "C:\Program Files (x86)\nodejs\node_modules\npm"
  #- npm install node-gyp@latest
  #- cd "C:\dev2\node-mapnik"
  - node --version
  - npm --version
  #- node-gyp --version
  - icacls lib\
  - ps: Get-ChildItem -Path lib\ | Get-Acl
  - scripts\build_against_sdk_00-START-HERE.bat
  - icacls lib\binding\
  - ps: Get-ChildItem -Path lib\binding | Get-Acl

build: off
test: off
deploy: off
