version: 1.0.{build}

clone_folder: c:\dev2\node-mapnik

environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: s1us6xb8U2EqlaVYtoVMtulfgMdX4VVEKgTF+Eft104gWja1GG0Blf6cMJtG7Yu3
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10

platform:
#  - x64
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node -e "console.log('node version ' + process.version + ' architecture ' + process.arch);"
  - node --version
  - npm --version
  # upgrade node-gyp to ensure it knows about msvs 2013
  - npm install node-gyp
  - icacls lib\
  - ps: Get-ChildItem -Path lib\ | Get-Acl
  - scripts\build_against_sdk_00-START-HERE.bat
  - icacls lib\binding\
  - ps: Get-ChildItem -Path lib\binding | Get-Acl
  - npm test 2>&1
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp --msvs_version=2013 package publish 2>&1

build: off
test: off
deploy: off
